[package]
name = "database-macro"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.11.3"
proc-macro2 = "1.0.101"
quote = "1.0.40"
sqlparser = "0.58.0"
syn = "2.0.106"

[lib]
proc-macro = true
